import { Box } from '@mui/material'
import React from 'react'

const Feed = () => {
  return (
    <Box bgcolor="yellow" flex={8} p={2}>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quasi unde exercitationem facilis possimus enim ex quos quia necessitatibus! Eius vero delectus quas. Voluptatibus ullam eligendi vero error in maxime veniam.
        Officiis, aliquid cum! Nostrum obcaecati soluta asperiores ipsa laborum incidunt explicabo doloremque suscipit in quas tempore ea, animi assumenda, dignissimos veritatis ex adipisci ullam rerum iste eveniet dolore. Delectus, error.
        Cum, odio, placeat possimus vero beatae hic accusantium nemo a, est aut ab aliquam eos. Corporis et illum, distinctio reprehenderit ex eos hic dolorum ut voluptatibus. Sapiente magnam quisquam possimus.
        Distinctio illo ipsum sequi repudiandae cumque obcaecati. Deserunt architecto nostrum accusantium quaerat quae iusto voluptatem, consequatur repudiandae laborum magnam. Quidem vitae ex eum ut soluta quaerat sequi, consequatur ratione rem!
        Repellendus nam voluptatum iusto magni, facere optio voluptatem repellat eius inventore quos sequi recusandae? Obcaecati consequuntur quod, explicabo accusantium corporis culpa magni sapiente! Quia totam vitae quasi vero minima doloribus.
        Temporibus hic porro, quasi nobis repellat sit delectus! Veritatis animi sint nulla quibusdam earum deserunt vel quas dolor voluptatum voluptas hic provident aspernatur ut nemo recusandae, ducimus aperiam, dignissimos est?
        Veritatis placeat rem error neque. Consequuntur repudiandae reiciendis saepe reprehenderit. Veritatis quae quibusdam magni ipsam molestias repellendus labore voluptate assumenda cum. Possimus nam quo laborum totam vel molestiae vitae. Corporis.
        Expedita fugiat illum eaque aspernatur totam quae quibusdam voluptatem dolores rerum maxime, blanditiis accusantium iusto molestias, ut corporis iure ex quod quaerat harum eligendi odit beatae consequatur! Est, repellat ipsum!
        Exercitationem saepe officiis deserunt ad sunt officia dolorum possimus doloremque. Pariatur odit consequuntur nihil, quis ratione architecto temporibus molestias repellendus necessitatibus, enim aperiam, molestiae voluptatum aspernatur. Voluptatum ut saepe sunt.
        Aspernatur ipsa dolores sit nulla harum, fuga officia voluptates ea autem reiciendis excepturi quibusdam veritatis deserunt mollitia, in, quisquam aliquam a ipsum. Autem possimus sequi nobis velit quia repudiandae quis.
        Earum placeat voluptate rem possimus. Iste ex non, consequuntur fugiat consequatur suscipit aperiam corrupti vero ullam voluptatibus quae voluptatem blanditiis saepe delectus numquam, eum facilis mollitia deleniti corporis, officia error.
        Atque, mollitia soluta explicabo obcaecati aliquam quo quae quisquam blanditiis voluptate deserunt accusamus voluptatum vero numquam architecto molestias doloribus nobis, ipsa velit esse neque? Recusandae magnam beatae repellat voluptate atque.
        Assumenda voluptate hic rem, numquam illum deleniti atque tempore exercitationem qui voluptatem unde! Tempora quae quia et unde? Tempore quasi vitae sunt fugiat id facilis ipsa eaque maiores voluptates maxime!
        Labore totam vel ratione architecto saepe dignissimos adipisci quisquam, ut optio natus laboriosam repellendus quas quam iure commodi. Pariatur soluta molestias aperiam sed. Temporibus non praesentium, iure ratione magnam unde.
        Ipsam similique quia consequatur reiciendis rerum earum maxime praesentium! Repellendus cum, aliquam aperiam nostrum illum unde ipsam perferendis labore necessitatibus officia odit, consectetur eum, molestiae ducimus! Harum, quo at. Veniam!
        Vel vitae eos cum laudantium mollitia at totam nulla rem odio. Rerum laborum corporis, impedit cum accusamus repellendus quasi? Expedita corporis suscipit hic veniam nostrum iusto consequatur in eveniet minima.
        Qui ut omnis eius commodi molestias sequi officiis ratione quam eligendi possimus dolore suscipit reprehenderit nam illo, praesentium magni excepturi accusantium, ad ullam? Placeat vitae nam repudiandae odio distinctio. Quisquam.
        Ea dolorum esse minus et doloribus, officia quisquam. Corrupti dolorum facere repudiandae nostrum, veritatis asperiores fugiat est quam, aliquam laborum adipisci consectetur officiis itaque. Ab harum blanditiis cumque atque nulla.
        Iusto, quam vel! Possimus quibusdam itaque mollitia eius adipisci consectetur officiis molestiae? Unde ab delectus atque impedit libero corporis tempore voluptates omnis beatae eaque esse, quae provident voluptatem et nihil?
        Corrupti vel aliquam dolore recusandae architecto libero sapiente repudiandae ipsam iure distinctio porro obcaecati doloremque atque doloribus incidunt hic nihil laudantium soluta numquam tempora, ex deleniti aperiam voluptates. Ex, quae?
        Qui vel minus fuga tempore nam hic natus. Tempore quo sunt officia repudiandae magni ipsam aspernatur voluptas perspiciatis id beatae. Eveniet deleniti autem officia, sint ullam dolorem minus? Possimus, nostrum?
        Non error tempora, necessitatibus maxime aut recusandae fugit sit aspernatur nesciunt vero odit alias asperiores dolor reiciendis quaerat suscipit molestias impedit in molestiae, sunt numquam? Magnam a ratione cumque adipisci.
        Amet repudiandae perspiciatis sit ad aliquid. Culpa iure rerum odio minus dicta fugit ipsum cum eos nemo eaque et, reiciendis ratione qui dolorum cupiditate harum autem! Voluptate, deleniti sunt! Nostrum.
        Molestiae placeat nulla sint vel dolorem, inventore vitae dolorum excepturi ut sunt numquam libero, eius laborum itaque voluptatibus iure maiores ipsam veniam laudantium animi et, totam temporibus. Sunt, provident cumque?
        Rem, possimus officia? Molestiae iure natus alias non cum, deleniti facilis sequi voluptas sed ullam! Harum dolore excepturi modi obcaecati laboriosam nihil odit enim necessitatibus ut assumenda. Dicta, numquam voluptatem?
        Impedit ipsam, quasi similique officiis laudantium excepturi eligendi corporis asperiores id pariatur quis dolores a repellendus. Fuga dolore minus distinctio illum quidem consequuntur culpa voluptate nesciunt eos expedita? Numquam, nisi!
        Velit asperiores eligendi architecto itaque veniam dolorem laboriosam quos? Pariatur, cumque fugit exercitationem explicabo quod reprehenderit fugiat suscipit voluptate illo id blanditiis autem voluptates. Dolor numquam quod recusandae dolores eos!
        Repellendus dolores quas nesciunt dicta veniam, voluptas sapiente iste, quae esse fuga adipisci soluta? Repellendus itaque est illo, porro omnis, temporibus accusantium magnam, alias dolorum vel similique praesentium dicta sint.
        Adipisci delectus, odit quia, quo, illo rerum porro aliquid natus obcaecati fugit nostrum magnam? Earum delectus ullam dolor, libero numquam cumque nemo corrupti vero excepturi, perspiciatis sit iure assumenda in.
        Illo, ea dolor magni quidem nostrum nesciunt dignissimos eius modi autem omnis quo expedita accusantium. Nobis tempora aliquam eligendi ad minus rerum quibusdam? Esse dignissimos unde quidem, ullam quae est.
        Repellendus eius saepe quibusdam possimus fugit nam tempore commodi. Cupiditate maxime aliquam doloremque, nihil numquam et facere culpa, magni laboriosam atque at, libero facilis. Aut aliquam blanditiis quos? Molestiae, modi.
        Laudantium dolorum quisquam minima quae assumenda animi incidunt delectus atque ab, voluptatem, provident asperiores, error doloremque optio repellat nostrum voluptate illo! Ipsum reiciendis repellendus numquam quisquam recusandae adipisci, temporibus amet.
        Ullam modi libero assumenda iusto inventore enim quod rem vero reiciendis tenetur eius placeat id, laboriosam, expedita nobis dolore, a quasi ex vitae at non cupiditate. Fugiat, totam harum. Debitis?
        Officia pariatur quod fuga quam, mollitia voluptatibus quasi vero, consectetur dignissimos dolor natus! Ratione, nulla! Neque accusantium, aut error impedit repellat voluptas obcaecati nobis dignissimos, ratione debitis voluptatibus animi commodi.
        Recusandae architecto, voluptatum autem cumque ut ipsum repellendus dignissimos, officiis facere id rerum expedita porro vero eaque praesentium voluptate quisquam. Libero hic cum totam incidunt autem laboriosam culpa quae at?
        Praesentium ut illo enim doloribus, a nostrum in tenetur rem commodi, at neque dicta provident necessitatibus vero adipisci earum voluptas, assumenda quasi. Quos quasi earum perferendis facilis nostrum provident laudantium.
        Repellendus veritatis cum adipisci incidunt officia nulla accusantium accusamus culpa, recusandae cupiditate fuga expedita voluptas quas consequatur amet consectetur. Tempora, aliquam? Quos quisquam suscipit unde soluta consequuntur amet aut ab?
        Laborum earum quo quam adipisci expedita odio sequi qui impedit? Sequi corrupti, fugiat ipsam, enim magni facere deleniti voluptates commodi dicta, molestiae similique libero esse laborum ratione omnis sed vel.
        Inventore ratione, explicabo voluptates iure libero voluptatum eum asperiores quam voluptate repudiandae, dolorum saepe reiciendis? Nemo perspiciatis earum temporibus laborum, exercitationem magni? Molestiae qui iste autem, voluptates incidunt culpa. Praesentium.
        Quo, sed. Tempore magnam dolor pariatur tenetur similique, ullam iusto fuga sequi consequuntur quam, consequatur doloremque. Odio veritatis a, ipsum et nulla ex consequatur totam debitis alias eius fugiat sed.
        Cupiditate magnam ab, recusandae earum odio nobis, necessitatibus nulla, asperiores blanditiis molestias rem quod enim fugit obcaecati sed nostrum? Assumenda soluta rem beatae necessitatibus veritatis libero nihil, similique odio eligendi?
        Aperiam reprehenderit mollitia deserunt possimus voluptas nemo quasi perspiciatis provident, quos nam! Earum, optio ipsam! Corporis quas aliquid, cupiditate voluptates maiores aspernatur asperiores ducimus debitis similique, magnam quisquam nam placeat.
        Sit nam non eius error eveniet, perferendis accusamus harum vero omnis iste cumque eaque nesciunt ipsam consequatur accusantium veniam mollitia pariatur. Quia molestias illum adipisci minima rem iure eos officia.
        Quia possimus ea doloremque minima! Iste nam sint nulla nemo ipsam? Vero dolores porro eaque ab ullam libero culpa ratione, cupiditate voluptates iusto aliquam, dicta rerum labore laudantium itaque. Numquam?
        Sequi, assumenda ratione! Totam neque magnam quia itaque ipsum eos commodi. Labore iusto, quo aperiam accusamus illum possimus earum unde. Esse iste corporis quo, quaerat mollitia corrupti magnam facilis incidunt.
        At unde sed praesentium eaque voluptatum, quod sequi numquam laboriosam, omnis quo natus alias reiciendis ut nesciunt autem suscipit assumenda accusamus pariatur. Veniam quam libero sequi enim perspiciatis a sit.
        Voluptas neque iste, ex assumenda, quidem minus necessitatibus ipsa ducimus, sequi magni porro eveniet consequatur repellat consequuntur tempore tenetur exercitationem illum fugit natus amet numquam enim eos recusandae ipsum? Maiores!
        Nesciunt dignissimos libero sit corrupti soluta veniam? Doloremque nemo porro quam sunt odit, itaque id repudiandae quis odio voluptatum quae dolorum maiores repellendus minus eaque suscipit? Eum minus similique minima.
        Fugiat eaque repellendus temporibus corrupti tempora ullam debitis, ratione molestiae consequatur error maxime officiis, provident corporis nostrum commodi distinctio illum, eveniet officia autem perferendis nulla nisi nam iste! Pariatur, praesentium.
        Explicabo modi repudiandae, eos ratione quae ut eveniet ea ipsam dolorem odio corrupti quaerat tenetur magni culpa illo. Repellendus, laborum temporibus voluptate dolores reprehenderit soluta odio maiores nesciunt magnam esse?
        Ipsam distinctio inventore tempora, accusantium, quisquam molestiae perspiciatis voluptatibus in nam provident alias earum optio voluptates veritatis quos, minus dolor doloribus eum. Non dolor perspiciatis nobis reiciendis quo recusandae optio!
        Hic nam est eius, aliquid neque beatae deleniti nisi? Ducimus accusantium quos id temporibus maxime, eligendi non alias distinctio doloribus accusamus consequuntur omnis, illo praesentium, itaque magni animi aliquid possimus.
        Natus, architecto. Qui a officia illo explicabo. Officiis tempora in blanditiis porro placeat non ratione, dolor accusantium, voluptates perferendis voluptatem possimus sed! Eum, quidem similique sit nostrum odit consectetur nobis.
        Delectus autem ea, suscipit aperiam voluptate architecto voluptas sed corporis, odio perspiciatis quo ipsum perferendis. Et, repellendus quis, at atque hic dolores suscipit possimus iusto sequi reprehenderit sint recusandae blanditiis!
        Aperiam doloribus labore vero est, mollitia rerum, quia neque numquam unde expedita temporibus sunt corporis, fuga laudantium illo quos molestias cum. Esse laudantium a vel ullam quisquam sunt adipisci officia.
        Possimus necessitatibus laboriosam, voluptatem, dolorem quidem deserunt laudantium vitae harum temporibus ad mollitia ipsam tempora officia facere sequi. Dicta necessitatibus, impedit omnis nisi asperiores nulla adipisci nihil provident natus tempore?
        Asperiores quidem reprehenderit excepturi possimus nemo autem, odio reiciendis, eligendi quasi expedita ut eum laudantium. Inventore voluptatibus culpa repellendus dolor itaque nihil eum cum rerum, optio quasi laudantium ipsum suscipit.
        Dolor a aliquid, sequi minus, ipsa totam, assumenda labore rerum recusandae ipsum voluptates amet aut molestiae! Expedita enim non dolorem assumenda at, quae commodi consequatur quisquam a, labore, ad veniam.
        Eum ea illo sed dolorum soluta nobis asperiores incidunt molestias. Commodi tempore eaque magnam maxime earum ducimus? Ex voluptatem nemo repudiandae nobis sequi, voluptatibus exercitationem fuga dolor, excepturi est mollitia!
        Id, quas vel itaque ea magnam aut nulla tempore velit, vero dolor officiis consequatur eius similique, dolorum omnis voluptates natus porro! Excepturi expedita maiores dolorem, illo sit quidem nostrum accusamus.
        Commodi dolorem at reprehenderit alias. Cumque ea consectetur officia odit explicabo expedita alias, quo quis. Accusantium similique non nisi fugit ad ipsa doloremque? Explicabo alias itaque, perspiciatis voluptate laborum quibusdam.
        Debitis inventore rem dolorum deserunt reprehenderit quasi explicabo hic maiores eveniet esse aperiam, incidunt at, voluptatum quae! Ducimus est, recusandae, iste consequuntur esse, corporis placeat quam labore voluptatibus vel natus?
        Molestias quisquam deleniti repudiandae repellendus, itaque ad repellat neque vel odit veniam debitis perferendis asperiores dignissimos officia culpa voluptate sed maiores id recusandae temporibus blanditiis, at eius? Nisi, maiores perferendis?
        Ea neque amet vero omnis consequuntur rerum repellat fugiat provident commodi soluta illum vitae eligendi possimus exercitationem dicta, fuga quasi? Tenetur tempora sapiente reiciendis velit voluptatem eligendi consectetur autem placeat!
        Beatae rerum, ullam facilis voluptas adipisci ab nisi mollitia atque provident delectus ipsam. Ducimus nihil earum natus ratione necessitatibus sint fugit similique, deserunt consectetur quia velit exercitationem consequatur est tenetur!
        Animi illo, nemo hic similique quod quas delectus, sint, blanditiis repellendus ex officia reiciendis vel corrupti voluptatem? Laboriosam, atque at vero optio illo veniam? Aperiam atque quidem repellat quis. Exercitationem!
        Possimus sequi aliquam dignissimos praesentium! Architecto eaque possimus quas saepe itaque, harum accusantium est laborum molestias. Et, odio recusandae hic repudiandae enim dolor quas voluptate labore sequi illo vel optio?
        Iste tempora, voluptate repellendus iure neque obcaecati sed, necessitatibus harum nisi nobis magnam quisquam, exercitationem aliquid consequatur voluptates. Incidunt repellat quia voluptatibus soluta amet ipsa maiores magni officiis culpa consequuntur.
        Unde culpa corporis neque cum alias saepe delectus, cumque labore deserunt quo aut necessitatibus voluptatibus est totam atque architecto ipsum, voluptas, tempore harum placeat quae? Numquam optio doloremque fuga voluptatem!
        Labore ratione obcaecati optio illum quibusdam quis debitis alias nulla quasi commodi. Est molestias distinctio sapiente, esse id perspiciatis, corporis dolores quas maiores dolorem, commodi optio? Rem ab ipsa fugit?
        Ab ut iure soluta mollitia at molestias nihil exercitationem, quisquam culpa, veniam quas tenetur sint doloribus dolore unde deleniti doloremque. Hic quam consectetur eligendi similique. Ratione neque ipsa obcaecati voluptate.
        Ex cumque minima iusto inventore odio iure voluptatum explicabo. Delectus eveniet ut consequuntur nobis. Quas, aperiam eaque. Vero amet rem possimus earum asperiores maxime, quae architecto provident eaque rerum? Assumenda.
        Culpa at atque blanditiis similique ipsa cupiditate nemo magni corrupti quidem, enim quo impedit delectus nobis libero saepe consequatur totam, maxime tempore porro quis eum! Eos fuga quasi ducimus asperiores.
        Inventore laboriosam quo est obcaecati blanditiis voluptates quis eveniet cum minus modi. Nobis quas sequi, officia distinctio praesentium laborum! Esse suscipit fugit vitae aperiam iste quasi eius commodi sint assumenda?
        Corrupti dignissimos explicabo sequi ut repellat ducimus. Tenetur quo labore cum sit laudantium, non veniam natus voluptates eos placeat cupiditate illum quia est aliquam quasi ipsa! Iste cum voluptas sit.
        Ut nesciunt ea aliquam sed error a minus id soluta obcaecati asperiores numquam dicta praesentium officiis sapiente accusantium labore sunt nostrum similique itaque, suscipit assumenda quibusdam. Accusamus sunt pariatur voluptatum?
        Hic obcaecati, quam non consectetur nobis architecto, ea, voluptatibus aut ex aspernatur dolorum laboriosam asperiores. Atque, illum ab. Quasi, officiis sunt quod illo explicabo laboriosam ab minima rerum quos ex!
        Labore amet ducimus natus nihil sit commodi, ab delectus. Laboriosam, reprehenderit similique! Ex veritatis optio perferendis necessitatibus voluptatibus magni ad voluptate provident maiores doloremque repellat tempora, vitae, doloribus perspiciatis aspernatur?
        At ad error, dolorem aspernatur deleniti quam nobis beatae porro repellat? Nulla corrupti provident molestias quaerat. Totam autem veniam, nisi neque ipsa perspiciatis cupiditate distinctio odio, explicabo unde praesentium rem.
        Quaerat minus tenetur voluptatibus, blanditiis ad eveniet ipsum rem molestiae repellendus architecto. Molestias eaque voluptatibus voluptates quisquam, molestiae magni corrupti ab ea veritatis, fugit illo, quo perspiciatis asperiores architecto harum?
        Dignissimos mollitia consequatur ipsum sit, facere nemo reprehenderit commodi eum? Porro id impedit unde laborum corrupti ducimus animi! Et totam maiores consequuntur delectus. Eveniet libero, iure ipsam ut cum deserunt?
        Voluptatem delectus, vel fugiat earum soluta totam officiis. Labore illum ipsa, at dolorem nihil quam porro veniam, dolorum commodi facilis ratione non soluta cupiditate! Sit ullam incidunt officia quibusdam porro!
        Ratione, quae! Consectetur, natus? Iste impedit accusamus explicabo vel beatae similique atque corrupti. Expedita doloremque in soluta facere consequuntur excepturi impedit labore repellendus et aliquid, aspernatur itaque quam assumenda tenetur.
        Modi accusamus itaque saepe autem repellat expedita omnis asperiores quisquam, ab dolorum, repellendus nisi incidunt exercitationem quam doloremque natus. Fuga sed quia dolor incidunt doloribus sunt deserunt ab voluptatibus dolorum.
        Ullam obcaecati libero iste harum tempore nulla vitae corrupti adipisci laborum voluptatum. Eveniet animi minus temporibus quos nostrum voluptates natus asperiores nisi iusto porro fugit consequatur pariatur debitis, voluptatibus esse!
        Beatae, laudantium aut! Earum hic harum facilis aut corrupti a exercitationem cupiditate reprehenderit optio, consequuntur ab ut facere error, veniam provident nisi qui. Aspernatur aperiam ipsa in molestias eaque nihil?
        Vel aliquam cum cupiditate, quam iusto tempore molestiae mollitia deleniti laboriosam rerum maiores voluptatum suscipit rem enim qui, ipsa aliquid deserunt facere quos. Est libero tempora perspiciatis deleniti blanditiis consequatur.
        Consectetur consequatur dolor odit ipsum voluptatum, adipisci incidunt omnis rem in distinctio dignissimos impedit non numquam eos, ex officiis repudiandae? Doloribus incidunt iste sapiente pariatur, provident laboriosam quam repellendus quibusdam.
        Perferendis, non dolorem culpa cumque neque exercitationem nulla soluta pariatur debitis quisquam, officiis, vitae iste earum incidunt magnam quidem praesentium sint dicta aliquid assumenda. Aliquam facilis soluta doloremque atque fugit!
        Voluptatibus nisi, corrupti doloremque, ab fugit necessitatibus asperiores illo voluptate nesciunt veritatis voluptas voluptates officia culpa sapiente libero, et harum distinctio delectus error nobis ut nihil praesentium iusto! Hic, enim.
        Asperiores similique quos est dignissimos. Ipsam nisi molestiae porro quaerat hic aut id voluptas culpa, natus aliquam, ipsa itaque nulla accusamus. Dignissimos, placeat officia. Corrupti quae natus eveniet sit accusantium?
        Nulla voluptatum assumenda rerum, quisquam illum saepe quasi sequi fuga, odit quae quibusdam iure soluta modi molestiae ipsum. Magnam blanditiis ipsam amet culpa nesciunt, dolorum facere! Aliquid similique incidunt reiciendis!
        Corporis illo quibusdam facilis minima, error minus odit cumque tempora provident facere quaerat assumenda? Perspiciatis voluptate fuga odio asperiores commodi repudiandae temporibus harum nobis. Amet esse provident eaque omnis qui?
        Est dignissimos quas quae recusandae inventore aliquid fugit suscipit natus dolorum animi, earum nam error, molestias distinctio numquam ullam tenetur itaque magnam ducimus necessitatibus. Accusamus maiores nesciunt deleniti omnis reiciendis?
        Consequuntur, iste odit. Nihil quia blanditiis ex illo asperiores. Laboriosam odit debitis voluptatibus sequi, inventore placeat voluptatum. Aliquid, deleniti in est officia doloribus saepe, illum provident modi quidem ullam id!
        Laudantium voluptatum voluptatem quisquam delectus, minus modi nemo non cupiditate animi ducimus, dolor aliquid reiciendis nesciunt odit culpa enim. Aliquid voluptates molestiae porro minima mollitia enim accusamus voluptatum deleniti omnis?
        Ratione qui eum in tempora voluptatum ab aliquid quae neque provident, illo consectetur iste nobis totam delectus dolorum error velit suscipit! Autem, porro! Nam dolore provident error dolores quis delectus?
        Id, atque est, nam harum modi dicta, quo dolores repellendus praesentium amet optio eius voluptatem deleniti consequatur eligendi incidunt veniam expedita saepe voluptates minus quas doloribus. Unde doloribus iusto suscipit.
        Dolores modi expedita reprehenderit quis minus nulla a quod excepturi atque suscipit autem alias odio facere sint praesentium corporis distinctio omnis ut consequatur tenetur, nam cupiditate. Sit dolorem nostrum dolores!
        Commodi aperiam fugit maxime! Consequuntur, exercitationem fuga magni odio a beatae aspernatur tempore commodi sunt quasi minus tenetur, labore omnis nulla facilis voluptas voluptate atque minima repellendus. Fugiat, quo quae.
    </Box>
  )
}

export default Feed